// Assuming Product is defined somewhere in your codebase
// import { Product } from "@/lib/types";

import hero from "@/public/images/hero.jpg";
import hero1 from "@/public/logo.png";

export const products = [
  {
    id: 1,
    name: "Organic Spinach",
    description: "Fresh, nutrient-rich organic spinach leaves. Perfect for salads, smoothies, or cooking.",
    price: 3.99,
    category: "leafy",
    unit: "250g bunch",
    stock: 15,
    discount: 0,
    featured: false,
    bestseller: true,
    seasonal: true,
    new: true,
    image: hero,
    image1: hero1
    
    // image: require("https://www.greendna.in/cdn/shop/products/English_Spinach__67562.jpg?v=1607938113"),
    // image1: "https://www.greendna.in/cdn/shop/products/English_Spinach__67562.jpg?v=1607938113",
    // image2: "https://assets.farmjournal.com/dims4/default/2c53260/2147483647/strip/true/crop/840x561+0+20/resize/800x534!/quality/90/?url=https%3A%2F%2Ffj-corp-pub.s3.us-east-2.amazonaws.com%2Fs3fs-public%2F2023-01%2FMy%20project-1%20%2824%29.jpg",
    // image3: "https://www.greendna.in/cdn/shop/files/palak43_0aa1ffba-424e-4f45-85ef-a71787914462_1200x1200.webp?v=1715600448",
    // image4: "https://cdn.shopify.com/s/files/1/0824/4857/files/spinach_large.jpg?v=1490961229",

  },
  // {
  //   id: 2,
  //   name: "Fresh Carrots",
  //   description: "Sweet and crunchy organic carrots. Great for snacking, cooking, or juicing.",
  //   price: 2.49,
  //   category: "root",
  //   unit: "500g pack",
  //   stock: 30,
  //   discount: 0,
  //   featured: true,
  //   bestseller: false,
  //   seasonal: false,
  //   new: false,
  //   image:"https://bcfresh.ca/wp-content/uploads/2021/11/Carrots.jpg",
  //   image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqAEprHBPrgPkseLGwVsQtHBn10sr_MbDX3g&s",
  //   image3:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQqXXHSOe3Wcano4yfZt7xZ1vdPGwtLYvmVg&s",
  //   image4:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKE1cuRTVdpbJZWMynAXLhbWbGFGfe_-F8DCWrpgKxNkiTGj2jcY2Va6URRbn6-Xa8kMg&usqp=CAU",
  // },
  // {
  //   id: 3,
  //   name: "Organic Tomatoes",
  //   description: "Juicy, vine-ripened organic tomatoes. Perfect for salads, sandwiches, or cooking.",
  //   price: 4.99,
  //   originalPrice: 5.99,
  //   category: "fruit",
  //   unit: "500g pack",
  //   stock: 25,
  //   discount: 15,
  //   featured: true,
  //   bestseller: true,
  //   seasonal: true,
  //   new: true,
  //   image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUNv6KlI2NH2jllUtIN_OhE_mlzvWRJwYuWA&s",
  //   image2:"https://drearth.com/wp-content/uploads/tomato-iStock-174932787.jpg",
  //   image3:"https://i0.wp.com/katiespring.com/wp-content/uploads/2018/02/P1130463.jpg?resize=1024%2C682&ssl=1",
  //   image4:"https://www.planetnatural.com/wp-content/uploads/2013/03/organic-tomato-crop.jpg",
  // },
  // {
  //   id: 4,
  //   name: "Fresh Cucumber",
  //   description: "Crisp and refreshing organic cucumbers. Great for salads, sandwiches, or snacking.",
  //   price: 1.99,
  //   category: "fruit",
  //   unit: "Each",
  //   stock: 40,
  //   discount: 0,
  //   featured: false,
  //   bestseller: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://www.growforagecookferment.com/wp-content/uploads/2023/08/preserve-cucumbers-featured.jpg",
  //   image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoZ1t8pc0XVXwHBO9NsLWhNrKXjubAFNNDow&s",
  //   image3:"https://i0.wp.com/post.healthline.com/wp-content/uploads/2022/06/cutting-board-cucumbers-1296x728-header.jpg?w=1155&h=1528",
  //   image4:"https://foodal.com/wp-content/uploads/2015/07/Fresh-Cucumber-Lots-of-Possibilities-and-low-In-Calories.jpg",
  // },
  // {
  //   id: 5,
  //   name: "Organic Kale",
  //   description: "Nutrient-dense organic kale. Perfect for salads, smoothies, or cooking.",
  //   price: 3.49,
  //   category: "leafy",
  //   unit: "200g bunch",
  //   stock: 20,
  //   discount: 0,
  //   featured: true,
  //   bestseller: false,
  //   seasonal: true,
  //   new: true,
  //   image:"https://images.squarespace-cdn.com/content/v1/5a470bc3b7411c6102f6abfc/1615344892779-KL2JRIM4EL90KN5NAML8/159320045_10222610804556667_2502625396641169201_n.jpg?format=2500w",
  //   image2:"https://as1.ftcdn.net/v2/jpg/02/94/36/86/1000_F_294368609_7SKMcTSWafs33QBqxGTn7yr8yQYngMid.jpg",
  //   image3:"https://www.rawl.net/media/620876/organic_kale_1200.jpg",
  //   image4:"https://www.ewg.org/sites/default/files/styles/wide_standard_xl/public/blog/KaleCHBlog.jpg?h=2e181f1f&itok=23HiXRED",
  // },
  // {
  //   id: 6,
  //   name: "Bell Peppers",
  //   description: "Colorful organic bell peppers. Great for salads, stir-fries, or stuffing.",
  //   price: 4.99,
  //   category: "fruit",
  //   unit: "3 pack (red, yellow, green)",
  //   stock: 25,
  //   discount: 0,
  //   bestseller: true,
  //   featured: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://aanmc.org/wp-content/uploads/2023/09/bell-peppers-1200x800-1-1024x683.jpg",
  //   image2:"https://healthyfamilyproject.com/wp-content/uploads/2020/05/Bell-Peppers-background.jpg",
  //   image3:"https://blog.lexmed.com/images/librariesprovider80/blog-post-featured-images/shutterstock_1901644783.jpg?sfvrsn=1986920b_0",
  //   image4:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzS54oSj68uRK3ZSWsiSNJp30HSpIWW6aDNg&s",
  // },
  // {
  //   id: 7,
  //   name: "Organic Potatoes",
  //   description: "Versatile organic potatoes. Perfect for roasting, mashing, or frying.",
  //   price: 3.99,
  //   category: "root",
  //   unit: "1kg bag",
  //   stock: 50,
  //   discount: 0,
  //   featured: false,
  //   bestseller: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ50kOIf3s2YknST25PHxiPKL1yHPqQwo2zkQ&s",
  //   image2:"https://produits.bienmanger.com/36865-0w470h470_Organic_Potato_From_France.jpg",
  //   image3:"https://organicmandya.com/cdn/shop/files/Potato.jpg?v=1721375270&width=1000",
  //   image4:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg3weVmLu1LelK7YPFFX24pVKHiTMd7J9juA&s",
  // },
  // {
  //   id: 8,
  //   name: "Fresh Broccoli",
  //   description: "Nutritious organic broccoli. Great for stir-fries, steaming, or roasting.",
  //   price: 2.99,
  //   category: "fruit",
  //   unit: "Head",
  //   stock: 35,
  //   discount: 0,
  //   featured: true,
  //   bestseller: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,w_730/k%2Farchive%2Fd852987f86aeae8b65926f9e7a260c28285ea744",
  //   image2:"https://www.freshaisle.com/cdn/shop/files/fresh-broccoli-exotic-vegetables-873.jpg?v=1739195252",
  //   image3:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvavSU9e8VRJNkhVOa8mUHmZxZwvMp12y0fg&s",
  //   image4:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaZk9OaoEK4xg2ilrD5tzmSVayjqc9x66jFRAdc8GHXR2k-WgjzwQBrOiBNpzXPUhffZ8&usqp=CAU",
  // },
  // {
  //   id: 9,
  //   name: "Organic Lettuce",
  //   description: "Crisp organic lettuce. Perfect for salads, sandwiches, or wraps.",
  //   price: 2.49,
  //   category: "leafy",
  //   unit: "Head",
  //   stock: 30,
  //   discount: 0,
  //   featured: false,
  //   bestseller: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://farmlinkhawaii.com/cdn/shop/files/organic_20romaine-800x533.jpg?v=1724305179",
  //   image2:"https://calorganicfarms.com/wp-content/uploads/2017/10/Green-Romaine-Lettuce.jpg",
  //   image3:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3qqG5tjIoor2vr4Zo6dBLUQtzBZxNqxxz2w&s",
  //   image4:"https://www.edenbrothers.com/cdn/shop/files/lettuce-organic-little-gem-flo-1.jpg?v=1724261956",
  // },
  // {
  //   id: 10,
  //   name: "Fresh Onions",
  //   description: "Flavorful organic onions. Essential for cooking and adding flavor to dishes.",
  //   price: 1.99,
  //   category: "root",
  //   unit: "500g bag",
  //   stock: 45,
  //   discount: 0,
  //   featured: true,
  //   bestseller: false,
  //   seasonal: true,
  //   new: true,
  //   image:"https://produits.bienmanger.com/36700-0w470h470_Organic_Red_Onion_From_Italy.jpg",
  //   image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThwYBQodnnF4OPbJf-aeixd7cgmltyESE5CA&s",
  //   image3:"https://www.allrecipes.com/thmb/7nWWrzm6z9vjBZJaGi-mS_vcp6I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/What-Are-Onions-4x3-3e7ceaa0405c4da6bfcaa929b4640a52.jpg",
  //   image4:"https://m.media-amazon.com/images/I/51DJ-9xkuQL._AC_UF1000,1000_QL80_.jpg",
  // },
  // {
  //   id: 11,
  //   name: "Organic Garlic",
  //   description: "Aromatic organic garlic. Perfect for adding flavor to a wide variety of dishes.",
  //   price: 2.29,
  //   category: "herbs",
  //   unit: "3 bulb pack",
  //   stock: 40,
  //   discount: 0,
  //   featured: false,
  //   bestseller: true,
  //   seasonal: false,
  //   new: false,
  //   image:"https://www.greendna.in/cdn/shop/products/garlic-1_600x.jpg?v=1555938714",
  //   image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT92M-XG7qUtaXFUBWSsMi3ZT2PD3cA9I_MSw&s",
  //   image3:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbZ0WGrGX311l4_fmiKZK8RYf7yacF1g2ddQ&s",
  //   image4:"https://freshindiaorganics.com/cdn/shop/products/Garlic-Edited.jpg?v=1566199531",
  // },
  // {
  //   id: 12,
  //   name: "Fresh Cilantro",
  //   description: "Fragrant organic cilantro. Great for garnishing and adding flavor to dishes.",
  //   price: 1.79,
  //   category: "herbs",
  //   unit: "Bunch",
  //   stock: 25,
  //   discount: 0,
  //   new: true,
  //   featured: true,
  //   bestseller: false,
  //   seasonal: true,
  //   image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSb_DP2k6JgkWF8mUVnntvwh4UOj0b82f2eQ&s",
  //   image2:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzZ8B6VNh672Cs5JiG7Zmit5-SjjoljqIMEg&s",
  //   image3:"https://i5.walmartimages.com/seo/Fresh-Cilantro-Bunch_3c692ae5-58c5-4e87-abf7-1ff4c79cce8c.e8683ca8b44b72dab407cb5784864404.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
  //   image4:"https://www.shopfreshandgreen.com/cdn/shop/products/Cilantro_300x300.png?v=1743777066",
  // },
  // {
  //   id: 13,
  //   name: "Organic Zucchini",
  //   description: "Tender organic zucchini. Versatile for grilling, sautéing, or baking.",
  //   price: 2.49,
  //   category: "fruit",
  //   unit: "Each",
  //   stock: 30,
  //   discount: 0,
  //   seasonal: true,
  //   featured: false,
  //   bestseller: true,
  //   new: false,
  //   image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5JwCrHHAlP93t2Trt1Fb1ju23dGplLTWkJQ&s",
  //   image2:"",
  //   image3:"",
  //   image4:"",
  // },
  // {
  //   id: 14,
  //   name: "Fresh Beets",
  //   description: "Sweet organic beets. Great for roasting, juicing, or adding to salads.",
  //   price: 3.49,
  //   originalPrice: 3.99,
  //   category: "root",
  //   unit: "500g pack",
  //   stock: 20,
  //   discount: 10,
  //   new: true,
  //   image:"https://cdn-ilcomcj.nitrocdn.com/gQjEJqDFNhrAqazkRmLHUSeYhSESocTY/assets/images/optimized/rev-bf822ef/trainright.com/wp-content/uploads/2016/09/Beets.jpg",
  // },
  // {
  //   id: 15,
  //   name: "Organic Mint",
  //   description: "Refreshing organic mint. Perfect for teas, cocktails, or garnishing.",
  //   price: 1.99,
  //   category: "herbs",
  //   unit: "Bunch",
  //   stock: 15,
  //   discount: 0,
  //   seasonal: true,
  //   featured: false,
  //   bestseller: true,
  //   new: false,
  //   image:"https://organicmandya.com/cdn/shop/files/MintLeaves.jpg?v=1721375044&width=1000",
  //   image2:"",
  //   image3:"",
  //   image4:"",
  // },
  // {
  //   id: 16,
  //   name: "Fresh Cauliflower",
  //   description: "Versatile organic cauliflower. Great for roasting, steaming, or making cauliflower rice.",
  //   price: 3.99,
  //   category: "fruit",
  //   unit: "Head",
  //   stock: 25,
  //   discount: 0,
  //   featured: true,
  //   bestseller: false,
  //   seasonal: true,
  //   new: true,
  //   image:"https://www.marthastewart.com/thmb/XI9trFybfFDa5jFOP1lgKSwuv6c=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ms-cauliflower-getty-6f049e7cc14442fe8ec14ac7fdfa8070.jpg",
  //   image2:"",
  //   image3:"",
  //   image4:"",
  // },
];
